DolphiOrdersCore/Controllers/ExchangeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DolphiOrdersCore.Miscellaneous;
using Microsoft.AspNetCore.Mvc;

namespace DolphiOrdersCore.Controllers
{
    public class ExchangeController : Controller
    {
        private readonly Exchanger1C _exchanger;
        public ExchangeController(Exchanger1C exchanger)
        {
            _exchanger = exchanger;
        }
        [HttpPost]
        public JsonResult DoExchange([FromForm]string inputMessage)
        {
            var outputMessage = _exchanger.PerformExchangeWith1C(inputMessage);
            return Json(outputMessage);
        }
        public IActionResult Test(string param)
        {
            return Json(param);
        }

    }
}

DolphiOrdersCore/Controllers/FileUploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using DolphiOrdersCore.Miscellaneous;
using DolphiOrdersCore.Models.Concrete;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DolphiOrdersCore.Controllers
{
    public class FileUploadController : Controller
    {
        IHostingEnvironment _appEnvironment;
        ProductContext db;
        Exchanger1C _exchanger;

        public FileUploadController(IHostingEnvironment appEnvironment, ProductContext context, Exchanger1C exchanger)
        {
            _appEnvironment = appEnvironment;
            db = context;
            _exchanger = exchanger;
        }

        public IActionResult UploadDialog(string title)
        {
            ViewData["Title"] = title;
            return View();
        }

        [HttpPost]
        public IActionResult UploadExchangeFile(IFormFile uploadedFile)
        {
            Stream stream =  uploadedFile.OpenReadStream();
            StreamReader reader = new StreamReader(stream);
            string filesData = reader.ReadToEnd();
            string res = _exchanger.PerformExchangeWith1C(filesData);
            return Content(res);
        }
    }
}

DolphiOrdersCore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DolphiOrdersCore.Models;
using DolphiOrdersCore.Models.Concrete;
using DolphiOrdersCore.Models.Entities;
using DolphiOrdersCore.Models.Infrastructure;
using DolphiOrdersCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.Extensions.Logging;
using DolphiOrdersCore.Infrastructure.ViewModels;

namespace DolphiOrdersCore.Controllers
{
    public class HomeController : Controller
    {
        ProductContext db;
        public int PageSize = 10;

        public HomeController(ProductContext context)
        {
            db = context;
            //db.GetService<ILoggerFactory>().AddProvider(new MyLoggerProvider());
        }

        public IActionResult List(Guid productGroupId, int page = 1)
        {
            ProductListViewModel productListViewModel = new ProductListViewModel
            {
                ProductSummaries = db.Products
                .OrderBy(p => p.Id)
                .SelectMany(p=>db.ProductPrices.Where(pp => pp.PriceTypeId == Guid.Empty && p.Id== pp.ProductId).DefaultIfEmpty(), (p, pp) => new ProductSummaryModel { Product = p, Price = pp.Price!=null? pp.Price:0 })
                .Where(ps => productGroupId == Guid.Empty || ps.Product.ProductGroup.Id == productGroupId)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),

                PagingInfo = new PagingInfo { CurrentPage = page, ItemsPerPage = PageSize, TotalsItems = db.Products.Count(p => productGroupId == Guid.Empty || p.ProductGroup.Id == productGroupId) },

                CurrentProductGroupId = productGroupId
                
            };
            return View(productListViewModel);
        }

        [HttpGet]
        public IActionResult Buy(Guid id, Cart cart)
        {
            if (id == null) return BadRequest("Product not found");
            cart.AddItem(new Product { Id = (Guid)id }, 1, 10);
            ViewBag.ProductId = id;
            return View();
        }

        [HttpPost]
        public IActionResult Buy(Order order)
        {

            return View();
        }




        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DolphiOrdersCore/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

DolphiOrdersCore/Views/Home/Buy.cshtml
@{
    ViewData["Title"] = "Buy";
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
<title>Добавление товара в корзину</title>
</head>
<body>
<form method="post">
    <input type="hidden" value=@ViewBag.ProductId name="Id"/>
    <table>
        <tr><td>Имя</td><td> <input type="text" name="Name" /></td></tr>
        <tr><td>Фамилия</td><td> <input type="text" name="Surname" /></td></tr>
        <tr><td>Телефон</td><td> <input type="text" name="Phone" /></td></tr>
        <tr><td><input type="submit" value="Отправить" /></td><td></td></tr>
    </table>
   
</form>
</body>
</html>

DolphiOrdersCore/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    Dolphi Corporation<br />
    Beresinskaya 24a<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DolphiOrdersCore/Views/Home/List.cshtml
@using DolphiOrdersCore.Infrastructure.Helpers
@model DolphiOrdersCore.Infrastructure.ViewModels.ProductListViewModel
@{
    //Layout = null;
}

<!DOCKTYPE html>

    <html>
    <head>
        <title>Список товаров Долфи</title>
    </head>
    <body>
        <h1>Товары</h1>

        @foreach (var item in Model.ProductSummaries)
        {
            @await Html.PartialAsync("ProductSummary", item);
        }

        <a asp-controller="FileUpload" asp-action="UploadDialog" asp-route-title="Выбирите файл обмена от 1С">Загрузить файл обмена из 1С</a>

        <form asp-controller="Exchange" asp-action="DoExchange" method="post">

            <input type="hidden" name="inputMessage" value='{
        "UnloadingDate": "2018-07-11T13:42:22Z",
        "Catalog.ProductGroups": [{
                   "Id": "1c5b0bfe-7ffb-11de-8cc6-00248c29c07e",
                    "Code1C": "00034",
                    "Name": "!!Бандажі Medtextile"},
                   {
                    "Id": "b738f3f5-01ce-11e8-97d0-002590967b1c",
                      "Code1C": "00081",
                      "Name": "Бандажі кругловязані MedTextile"
                    },
                      {
                      "Id": "0966d706-7fff-11de-8cc6-00248c29c07e",
                      "Code1C": "00042",
                      "Name": "Бахіли"
                     }],
        "Catalog.Products": [{
                   "Id": "7147243a-8b79-11e0-b953-00248c29c07e",
                    "Code1C": "БАМ00104",
                    "Name": "Бандаж грижовий ліво- та правосторонній, розмір S, люкс",
                    "Article": "5001 S_люкс",
                    "ProductGroupId": "b738f3f5-01ce-11e8-97d0-002590967b1c"},
                   {
                  "Id": "0af3bc54-3612-11e7-a4d2-002590967b1c",
                  "Code1C": "COM01804",
                  "Name": "Бахіли МР MedPlast 2 г",
                  "Article": "Бахіли МР 2 г",
                  "ProductGroupId": "0966d706-7fff-11de-8cc6-00248c29c07e"
                 },
                   {
                   "Id": "89a5bac5-e73a-11df-b355-00248c29c07e",                    "Code1C": "АПД00006",                   "Name": "Антиполіцай А4 (4х20х50) Економ",                   "Article": "10807 ЭК",                   "ProductGroupId": null                  }
                   ]}' />

            <div>
                <input type="submit" value="Post request" />
            </div>
        </form>
        @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { productGroupId = Model.CurrentProductGroupId, page = x }))
    </body>
</html>